version: '3.8'
services:
  db:
    image: postgres:15
    container_name: food-db
    environment:
      POSTGRES_DB: fooddb
      POSTGRES_USER: fooduser
      POSTGRES_PASSWORD: foodpass
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
